services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  hits:
    image: ghcr.io/konstfish/hits:latest
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379